name: favola_incantata
description: Favola Incantata - storie personalizzate per bambini con libro animato e voce narrante.
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.5
  flutter_piper_tts: ^0.5.2
  path_provider: ^2.1.6
  page_flip: ^0.2.5+1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/voices/paola/
